# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Charcuterie on the Lawn
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Come join Charcuterie on the Lawn for its second installment,
  a celebration of craft Charcuterie crafted by local chefs Shawn Bennigsdorf and Randy Brown.
  A large and diverse selection of cured meats, pates, and terrines will be available.
baseurl: "/charcuterie-on-the-lawn" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
